version: '3'
services:
    app:
        build: .
        command: python -u run.py
        ports:
            - 5000:5000
        volumes:
            - .:/app
        links:
            - mysql
        depends_on:
            - mysql
        container_name: testapp-flask
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: testapp
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        expose:
            - 3306
        container_name: testapp-mysql